export const FETCH_DIR = 'FETCH_DIR'
export const RECEIVE_DIR = 'RECEIVE_DIR'
export const INIT_DEPTH = 'INIT_DEPTH'
export const ADD_DEPTH = 'ADD_DEPTH'
export const MOVE_DEPTH = 'MOVE_DEPTH'
export const PLAY_ENDED = 'PLAY_ENDED'
export const PLAY_NEXT = 'PLAY_NEXT'
export const ADD_QUEUE = 'ADD_QUEUE'
