export const FETCH_DIR = 'FETCH_DIR'
export const RECEIVE_DIR = 'RECEIVE_DIR'
export const ADD_DEPTH = 'ADD_DEPTH'
export const UPDATE_DEPTH = 'UPDATE_DEPTH'
export const PLAY_ENDED = 'PLAY_ENDED'
export const PLAY_NEXT = 'PLAY_NEXT'
export const ADD_QUEUE = 'ADD_QUEUE'
