export const SET_FILES = 'set-files'
export const AUDIO_TRIGGER_NEXT = 'audio-trigger-next'
export const NOWPLAYING_ENDED = 'nowplaying ended'
export const FILE_ADDED = 'file added'
export const FILER_SET_DIR = 'filer-set-dir'
export const FILER_GET_DIR = 'filer-get-dir'
export const FILER_ADD_DEPTH = 'filer-add-depth'
export const DEPTH_UPDATED = 'depth:updated'
